export const REQUEST_FETCH_CUSTOM_DATASETS = "REQUEST_FETCH_CUSTOM_DATASETS";
export const REQUEST_APPROVE_CUSTOM_DATASET = "REQUEST_APPROVE_CUSTOM_DATASET";
export const REQUEST_DOWNLOAD_CUSTOM_DATASET = "REQUEST_DOWNLOAD_CUSTOM_DATASET";

export const SUCCESS_FETCH_CUSTOM_DATASETS = "SUCCESS_FETCH_CUSTOM_DATASETS" 
export const SUCCESS_APPROVE_CUSTOM_DATASET = "SUCCESS_APPROVE_CUSTOM_DATASET" 
export const SUCCESS_DOWNLOAD_CUSTOM_DATASET = "SUCCESS_DOWNLOAD_CUSTOM_DATASET" 
 
export const FAILURE_FETCH_CUSTOM_DATASETS = "FAILURE_FETCH_CUSTOM_DATASETS"; 
export const FAILURE_APPROVE_CUSTOM_DATASET = "FAILURE_APPROVE_CUSTOM_DATASET"; 
export const FAILURE_DOWNLOAD_CUSTOM_DATASET = "FAILURE_DOWNLOAD_CUSTOM_DATASET"; 
