export const REQUEST_FETCH_DATASETS = "REQUEST_FETCH_DATASETS";
export const REQUEST_CREATE_DATASET = "REQUEST_CREATE_DATASET";
export const REQUEST_FILE_INPUT = "REQUEST_FILE_INPUT";
export const REQUEST_LINE_INPUT = "REQUEST_LINE_INPUT";

export const SUCCESS_FETCH_DATASETS = "SUCCESS_FETCH_DATASETS" 
export const SUCCESS_CREATE_DATASET = "SUCCESS_CREATE_DATASET" 
export const SUCCESS_FILE_INPUT = "SUCCESS_FILE_INPUT" 
export const SUCCESS_LINE_INPUT = "SUCCESS_LINE_INPUT" 
 
export const FAILURE_FETCH_DATASETS = "FAILURE_FETCH_DATASETS"; 
export const FAILURE_CREATE_DATASET = "FAILURE_CREATE_DATASET"; 
export const FAILURE_FILE_INPUT = "FAILURE_FILE_INPUT"; 
export const FAILURE_LINE_INPUT = "FAILURE_LINE_INPUT"; 

