export const REQUEST_ALL_DATASET = "REQUEST_ALL_DATASET";
export const REQUEST_UPLOAD_DATASET = "REQUEST_UPLOAD_DATASET";
export const REQUEST_DATASET_DELETE = "REQUEST_DATASET_DELETE";

export const SUCCESS_ALL_DATASET = "SUCCESS_ALL_DATASET";
export const SUCCESS_UPLOAD_DATASET = "SUCCESS_UPLOAD_DATASET";
export const SUCCESS_DATASET_DELETE = "SUCCESS_DATASET_DELETE";

export const FAILURE_ALL_DATASET = "FAILURE_ALL_DATASET";
export const FAILURE_UPLOAD_DATASET = "FAILURE_UPLOAD_DATASET";
export const FAILURE_DATASET_DELETE = "FAILURE_DATASET_DELETE";


export const BASE_URL = "http://192.168.1.8:8080";