export const REQUEST_FETCH_LEADERBOARD = "REQUEST_FETCH_LEADERBOARD";
export const SUCCESS_FETCH_LEADERBOARD = "SUCCESS_FETCH_LEADERBOARD";
export const FAILURE_FETCH_LEADERBOARD = "FAILURE_FETCH_LEADERBOARD";

// export const REQUEST_FETCH_PROFILE = "REQUEST_FETCH_PROFILE";
// export const SUCCESS_FETCH_PROFILE = "SUCCESS_FETCH_PROFILE"
// export const FAILURE_FETCH_PROFILE = "FAILURE_FETCH_PROFILE";

export const REQUEST_FETCH_NEWLINE = "REQUEST_FETCH_NEWLINE";
export const SUCCESS_FETCH_NEWLINE = "SUCCESS_FETCH_NEWLINE"
export const FAILURE_FETCH_NEWLINE = "FAILURE_FETCH_NEWLINE";

export const REQUEST_SUBMIT_TRANSLATEDLINE = "REQUEST_SUBMIT_TRANSLATEDLINE";
export const SUCCESS_SUBMIT_TRANSLATEDLINE = "SUCCESS_SUBMIT_TRANSLATEDLINE"
export const FAILURE_SUBMIT_TRANSLATEDLINE = "FAILURE_SUBMIT_TRANSLATEDLINE";

export const REQUEST_LOGOUT = "REQUEST_LOGOUT";
export const SUCCESS_LOGOUT = "SUCCESS_LOGOUT";
export const FAILURE_LOGOUT = "FAILURE_LOGOUT";

export const BASE_URL = "http://192.168.1.8:8080";
// export const UPDATE_SESSION_EXPIRY = "UPDATE_SESSION_EXPIRY";