export const REQUEST_FETCH_LEADERBOARD = "REQUEST_FETCH_LEADERBOARD";
export const SUCCESS_FETCH_LEADERBOARD = "SUCCESS_FETCH_LEADERBOARD";
export const FAILURE_FETCH_LEADERBOARD = "FAILURE_FETCH_LEADERBOARD";

export const REQUEST_FULL_LEADERBOARD = "REQUEST_FULL_LEADERBOARD";
export const SUCCESS_FULL_LEADERBOARD = "SUCCESS_FULL_LEADERBOARD";
export const FAILURE_FULL_LEADERBOARD = "FAILURE_FULL_LEADERBOARD";

export const REQUEST_FETCH_NEWLINE = "REQUEST_FETCH_NEWLINE";
export const SUCCESS_FETCH_NEWLINE = "SUCCESS_FETCH_NEWLINE"
export const FAILURE_FETCH_NEWLINE = "FAILURE_FETCH_NEWLINE";

export const REQUEST_SUBMIT_TRANSLATEDLINE = "REQUEST_SUBMIT_TRANSLATEDLINE";
export const SUCCESS_SUBMIT_TRANSLATEDLINE = "SUCCESS_SUBMIT_TRANSLATEDLINE"
export const FAILURE_SUBMIT_TRANSLATEDLINE = "FAILURE_SUBMIT_TRANSLATEDLINE";


export const BASE_URL = "http://localhost:8080";
// export const UPDATE_SESSION_EXPIRY = "UPDATE_SESSION_EXPIRY";
