export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_FETCH_PROFILE = "REQUEST_FETCH_PROFILE";
export const REQUEST_LOGOUT = "REQUEST_LOGOUT";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const SUCCESS_FETCH_ID = "SUCCESS_FETCH_ID";
export const SUCCESS_FETCH_PROFILE = "SUCCESS_FETCH_PROFILE" 
export const SUCCESS_LOGOUT = "SUCCESS_LOGOUT";
export const FAILURE_FETCH_PROFILE = "FAILURE_FETCH_PROFILE"; 
export const FAILURE_FETCH_ID = "FAILURE_FETCH_ID";
export const FAILURE_LOGIN = "FAILURE_LOGIN";
export const FAILURE_LOGOUT = "FAILURE_LOGOUT";

export const BASE_URL = "http://192.168.1.8:8080";
export const UPDATE_SESSION_EXPIRY = "UPDATE_SESSION_EXPIRY";
export const REQUEST_FETCH_ID = "REQUEST_FETCH_ID";