export const REQUEST_REVIEWING_LINE = "REQUEST_REVIEWING_LINE";
export const REQUEST_APPROVE_LINE = "REQUEST_APPROVE_LINE";
export const REQUEST_REJECT_LINE = "REQUEST_REJECT_LINE";

export const SUCCESS_REVIEWING_LINE = "SUCCESS_REVIEWING_LINE";
export const SUCCESS_APPROVE_LINE = "SUCCESS_APPROVE_LINE";
export const SUCCESS_REJECT_LINE = "SUCCESS_REJECT_LINE";

export const FAILURE_REVIEWING_LINE = "FAILURE_REVIEWING_LINE";
export const FAILURE_APPROVE_LINE = "FAILURE_APPROVE_LINE";
export const FAILURE_REJECT_LINE = "FAILURE_REJECT_LINE";


export const BASE_URL = "http://localhost:8080";