export const REQUEST_REVIEWING_LINE = "REQUEST_REVIEWING_LINE";
export const REQUEST_LINE_REVIEW_ACTION = "REQUEST_LINE_REVIEW_ACTION";

export const SUCCESS_REVIEWING_LINE = "SUCCESS_REVIEWING_LINE";
export const SUCCESS_LINE_REVIEW_ACTION = "SUCCESS_LINE_REVIEW_ACTION";

export const FAILURE_REVIEWING_LINE = "FAILURE_REVIEWING_LINE";
export const FAILURE_LINE_REVIEW_ACTION = "FAILURE_LINE_REVIEW_ACTION";
