export const REQUEST_ALL_USERS_DATA = "REQUEST_ALL_USERS_DATA";
export const REQUEST_USER_DATA = "REQUEST_USER_DATA";
export const REQUEST_USER_WITHDRAW_DATA = "REQUEST_USER_WITHDRAW_DATA";
export const REQUEST_USER_DELETE = "REQUEST_USER_DELETE";

export const SUCCESS_ALL_USERS_DATA = "SUCCESS_ALL_USERS_DATA";
export const SUCCESS_USER_DATA = "SUCCESS_USER_DATA";
export const SUCCESS_USER_WITHDRAW_DATA = "SUCCESS_USER_WITHDRAW_DATA";
export const SUCCESS_USER_DELETE = "SUCCESS_USER_DELETE";

export const FAILURE_ALL_USERS_DATA = "FAILURE_ALL_USERS_DATA";
export const FAILURE_USER_DATA = "FAILURE_USER_DATA";
export const FAILURE_USER_WITHDRAW_DATA = "FAILURE_USER_WITHDRAW_DATA";
export const FAILURE_USER_DELETE = "FAILURE_USER_DELETE";

