export const REQUEST_FETCH_WITHDRAWS = "REQUEST_FETCH_WITHDRAWS";
export const REQUEST_WITHDRAW_REQUEST = "REQUEST_WITHDRAW_REQUEST";

export const SUCCESS_FETCH_WITHDRAWS = "SUCCESS_FETCH_WITHDRAWS";
export const SUCCESS_WITHDRAW_REQUEST = "SUCCESS_WITHDRAW_REQUEST";

export const FAILURE_FETCH_WITHDRAWS = "FAILURE_FETCH_WITHDRAWS";
export const FAILURE_WITHDRAW_REQUEST = "FAILURE_WITHDRAW_REQUEST";
